AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SSMLAMBDA:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::712115679703:role/Lambda-ssm-ec2'
      Events:
        stream:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:ap-south-1:712115679703:test
