AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Events:
        stream:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:ap-south-1:712115679703:test
