AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SSM:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'SSM'
      AutoPublishAlias: live
      Handler: index.handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::712115679703:role/Lambda-ssm-ec2'
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
  SNSTopic:
    Type: 'AWS::SNS::Topic'
